export const heroList = [
    { name: 'Abaddon', src: '/assets/img/heroes/1.png' },
    { name: 'Alchemist', src: '/assets/img/heroes/2.png' },
    { name: 'Axe', src: '/assets/img/heroes/3.png' },
    { name: 'Beastmaster', src: '/assets/img/heroes/4.png' },
    { name: 'Brewmaster', src: '/assets/img/heroes/5.png' },
    { name: 'Bristleback', src: '/assets/img/heroes/6.png' },
    { name: 'Centaur Warrunner', src: '/assets/img/heroes/7.png' },
    { name: 'Chaos Knight', src: '/assets/img/heroes/8.png' },
    { name: 'Clockwerk', src: '/assets/img/heroes/9.png' },
    { name: 'Dawnbreaker', src: '/assets/img/heroes/10.png' },
    { name: 'Doom', src: '/assets/img/heroes/11.png' },
    { name: 'Dragon Knight', src: '/assets/img/heroes/12.png' },
    { name: 'Earth Spirit', src: '/assets/img/heroes/13.png' },
    { name: 'Earthshaker', src: '/assets/img/heroes/14.png' },
    { name: 'Elder Titan', src: '/assets/img/heroes/15.png' },
    { name: 'Huskar', src: '/assets/img/heroes/16.png' },
    { name: 'Io', src: '/assets/img/heroes/17.png' },
    { name: 'Kunkka', src: '/assets/img/heroes/18.png' },
    { name: 'Legion Commander', src: '/assets/img/heroes/19.png' },
    { name: 'Lifestealer', src: '/assets/img/heroes/20.png' },
    { name: 'Lycan', src: '/assets/img/heroes/21.png' },
    { name: 'Magnus', src: '/assets/img/heroes/22.png' },
    { name: 'Abaddon', src: '/assets/img/heroes/1.png' },
    { name: 'Alchemist', src: '/assets/img/heroes/2.png' },
    { name: 'Axe', src: '/assets/img/heroes/3.png' },
    { name: 'Beastmaster', src: '/assets/img/heroes/4.png' },
    { name: 'Brewmaster', src: '/assets/img/heroes/5.png' },
    { name: 'Bristleback', src: '/assets/img/heroes/6.png' },
    { name: 'Centaur Warrunner', src: '/assets/img/heroes/7.png' },
    { name: 'Chaos Knight', src: '/assets/img/heroes/8.png' },
    { name: 'Clockwerk', src: '/assets/img/heroes/9.png' },
    { name: 'Dawnbreaker', src: '/assets/img/heroes/10.png' },
    { name: 'Abaddon', src: '/assets/img/heroes/1.png' },
    { name: 'Alchemist', src: '/assets/img/heroes/2.png' },
    { name: 'Axe', src: '/assets/img/heroes/3.png' },
    { name: 'Beastmaster', src: '/assets/img/heroes/4.png' },
    { name: 'Brewmaster', src: '/assets/img/heroes/5.png' },
    { name: 'Bristleback', src: '/assets/img/heroes/6.png' },
    { name: 'Centaur Warrunner', src: '/assets/img/heroes/7.png' },
    { name: 'Chaos Knight', src: '/assets/img/heroes/8.png' },
    { name: 'Clockwerk', src: '/assets/img/heroes/9.png' },
    { name: 'Dawnbreaker', src: '/assets/img/heroes/10.png' },
    { name: 'Bristleback', src: '/assets/img/heroes/6.png' },
    { name: 'Centaur Warrunner', src: '/assets/img/heroes/7.png' },
    { name: 'Chaos Knight', src: '/assets/img/heroes/8.png' },
]