export const heroList = [
    { name: 'Luna', src: '/assets/img/hero/character-1.jpg' },
    { name: 'Luna', src: '/assets/img/hero/character-2.jpg' },
    { name: 'Luna', src: '/assets/img/hero/character-3.jpg' },
    { name: 'Luna', src: '/assets/img/hero/character-4.jpg' },
    { name: 'Luna', src: '/assets/img/hero/character-1.jpg' },
    { name: 'Luna', src: '/assets/img/hero/character-2.jpg' },
    { name: 'Luna', src: '/assets/img/hero/character-3.jpg' },
    { name: 'Luna', src: '/assets/img/hero/character-4.jpg' },
    { name: 'Luna', src: '/assets/img/hero/character-1.jpg' },
    { name: 'Luna', src: '/assets/img/hero/character-2.jpg' },
    { name: 'Luna', src: '/assets/img/hero/character-3.jpg' },
    { name: 'Luna', src: '/assets/img/hero/character-4.jpg' },
    { name: 'Luna', src: '/assets/img/hero/character-1.jpg' },
    { name: 'Luna', src: '/assets/img/hero/character-2.jpg' },
    { name: 'Luna', src: '/assets/img/hero/character-3.jpg' },
    { name: 'Luna', src: '/assets/img/hero/character-4.jpg' },
    { name: 'Luna', src: '/assets/img/hero/character-1.jpg' },
    { name: 'Luna', src: '/assets/img/hero/character-2.jpg' },
    { name: 'Luna', src: '/assets/img/hero/character-3.jpg' },
    { name: 'Luna', src: '/assets/img/hero/character-4.jpg' },
]