import './globals.css';
import { Inter } from 'next/font/google';
import { PlayerDrawer } from '@/components/drawer';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <head>
                {/* FUNCKY THEME STYLE */}
                <link rel="stylesheet" href="assets/css/bootstrap.min.css"/>
                <link rel="stylesheet" href="assets/css/funky-style.css"/>
                <link rel="stylesheet" href="assets/css/owl.carousel.css"/>
                <link rel="stylesheet" href="assets/css/owl.transitions.css"/>
                <link rel="stylesheet" href="assets/css/color-green.css"/>
            </head>

            <body className={inter.className}>
                {children}
                <PlayerDrawer/>
            </body>
            
            {/* FUNCKY THEME SCRIPT */}
            <script type="text/javascript" src="assets/js/tether.min.js" async></script>
        </html>
    )
}
